### ISSUE TITLE
adafruit-pi-cam - error in line 567

### ISSUE THREAD

**Issue by lukaszmajewski** [adafruit/adafruit-pi-cam#1]
Turotial for this app is grat! but,....at the beginning an explanation. 
I use a 3.2 "LCD (LCD-PI32), because I'm waiting for Adafruit PiTFT LCD when it will be on sale. 

The installation went without problems, but when I type the command 
sudo python cam.py get an error message.: 

"File cam.py, line 567, in module pygame.mouse.set_visible (False) 
pygame.error: video system not initialized 

is there any solution for this? 

and last one - I'm not a I'm not an advanced user

Regards,
Lukasz

**Comment by ladyada** [comment]
You need to have the PiTFT and our kernel mods installed before running! :)

**Comment by ghost** [comment]
Hello...,

Hey i'm having the same problem as Lukasz mentioned above.. But i'm using LCD-PI33. But i need solution with this display only since i'm running out of my time. i have left only 6 days of time to submit my work.. 

Pls help me to do this i.e to solve 
"File cam.py, line 567, in module pygame.mouse.set_visible (False) 
pygame.error: video system not initialized"

i'm waiting for ur reply...
thanking you in advance..

**Comment by ladyada** [comment]
Please contact the LCD-PI33 seller for help and support thanks!

**Comment by ghost** [comment]
hi.....,

i'm sorry for asking the same again...
As i previously mentioned, i'm looking for using an app that is specially written for ur 2.8" display and i want it on LCD-PI33...
As i said i'm very new to linux and don't know to play with these kernel modules..

All my effort to create digital camera were failed and at the end i came to know about adafruit-pi-cam blog..

As i said I'm running out of my time and its very important for my project submission... It is a matter of our final exams.. 

There is no place for support in hwlevel.com site and with the hope i posted on rpi forum... But i didn't get any support from them...

i request u guys, someone pls spend few minutes of ur precious time for helping me to solve this...

My email id is 1)."siddarajudh@gmail.com"   2)."gowdakamala@gmail.com" 

Pls  pls pls help me to solve this...

my status - I can capture a image with camera preview on LCD-PI33 with the script 
"fbcp &
raspistill -t 2000 -fp
pkill fbcp"

**Comment by ladyada** [comment]
Please contact the LCD-PI33 seller for help and support thanks!

**Comment by Technicus** [comment]
I am having this problem also.  The 2.8 tft is installed and working. So is the touch screen.

**Comment by bezeefly** [comment]
I had the same problem with "pygame.error: video system not initialized". 

I referred to robertimorrison's solution in the following link: 
https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=73304

The problem is solved by changing the touchscreen environment variable.
