### ISSUE TITLE
Resolution is lower

### ISSUE THREAD

**Issue by bl4ckc00k1e** [adafruit/adafruit-pi-cam#10]
Hi,
i Have screen touch with 480x320, and the image of the camera is always in the left corner more small than the screen size... How can i put full size?? what is wrong in my raspberry 2?

I use noir Camera

**Comment by ladyada** [comment]
not supported

**Comment by bl4ckc00k1e** [comment]
The code dont support 480x320? or you dont wanna support it? 
I need to know to take time to resolve it or no...

**Comment by ladyada** [comment]
it does not support 480x320
we do not have time to add support for it
thx!
