### ISSUE TITLE
Request - Shutter Release Button

### ISSUE THREAD

**Issue by PhilipMcGaw** [adafruit/adafruit-pi-cam#5]
Use of the one or more of the GPIO buttons as shutter release.

**Comment by marsfan** [comment]
I second this. I would program the code, but my python knowledge is diddly squat.

**Comment by ladyada** [comment]
https://learn.adafruit.com/instant-camera-using-raspberry-pi-and-thermal-printer/system-setup
has some example code you might be able to use!
