### ISSUE TITLE
its not working for ada fruit 3.5 inch display

### ISSUE THREAD

**Issue by nikeshranjan2009** [adafruit/adafruit-pi-cam#7]
for adafruit 3.5 inch display the camera preview is not coming on full screen . its just covering the top corner. any help????/

**Comment by ladyada** [comment]
thats right, its for the 2.8" display (240x320) only

**Comment by nikeshranjan2009** [comment]
but i want for 3.5 inch screen

**Comment by nikeshranjan2009** [comment]
i have adafruit 3.5 inch tft is thr anything avilable for that

**Comment by nikeshranjan2009** [comment]
i have adafruit 3.5 inch tft is thr anything avilable for that

**Comment by nikeshranjan2009** [comment]
i have adafruit 3.5 inch tft is thr anything avilable for that
